### ISSUE TITLE
vanishing ancestry

### ISSUE THREAD

**Issue by brendangregg** [cimi/d3-flame-graphs#52]
Transitions look great, but if I click on a leaf the ancestry frames vanish. Would be good to keep them, faded, for visual context.

**Comment by cimi** [comment]
Makes sense, I had noticed this a while ago. I'll fix it.

I don't have any better ideas on how to indicate to the user that a node is unclickable other than changing the cursor to default instead of pointer. If you do I'd be happy to hear them. :)

**Comment by cimi** [comment]
Because d3 [considers the node value to be the sum of its children](https://github.com/mbostock/d3/pull/574) representing leaf nodes by themselves requires injecting an artificial child for each, with a value equal to the leaf node's value. This in turn affects d3's partition layout and indirectly the levels the nodes are rendered on.

I've chosen to disable zooming on leaf nodes and on nodes that span 100% of the width of the graph as it seems to be the least painful option. This way at least the user is prevented from seeing an empty graph. I don't see much value in zooming on leaves anyway, other than UI consistency in having all nodes behave the same.
